### ISSUE TITLE
Can you update the PyQt5 version?

### ISSUE THREAD

**Issue by ViCrack** [bytebutcher/decoder-plus-plus#42]
requirements
```
PyQt5>=5.15
```

Because Python310 may not be supported
```
C:\WINDOWS\system32>pip3 install decoder-plus-plus
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Collecting decoder-plus-plus
  Using cached https://mirrors.aliyun.com/pypi/packages/9e/48/a98911b4f1d8729b8adcfc90c45eef2d82531de91d803653906bbc12ea6f/decoder_plus_plus-1.2.6-py3-none-any.whl (264 kB)
Requirement already satisfied: hashid==3.1.4 in d:\programs\python310\lib\site-packages (from decoder-plus-plus) (3.1.4)
Requirement already satisfied: passlib==1.7.4 in d:\programs\python310\lib\site-packages (from decoder-plus-plus) (1.7.4)
Requirement already satisfied: filemagic==1.6 in d:\programs\python310\lib\site-packages (from decoder-plus-plus) (1.6)
Collecting QtAwesome==1.0.2
  Downloading https://mirrors.aliyun.com/pypi/packages/25/10/365b89bf87eef7e631bb2e32ff650b918925b5264cbf56d6748fea83b966/QtAwesome-1.0.2-py3-none-any.whl (862 kB)
     ---------------------------------------- 862.5/862.5 kB 1.0 MB/s eta 0:00:00
Collecting PyQt5==5.15
  Using cached https://mirrors.aliyun.com/pypi/packages/8c/90/82c62bbbadcca98e8c6fa84f1a638de1ed1c89e85368241e9cc43fcbc320/PyQt5-5.15.0.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "D:\Programs\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "D:\Programs\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "D:\Programs\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\Programs\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-hsif3_67\overlay\Lib\site-packages\sipbuild\api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-hsif3_67\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-hsif3_67\overlay\Lib\site-packages\sipbuild\project.py", line 594, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\Admin\AppData\Local\Temp\pip-install-htrqest9\pyqt5_dcc6844aa887475b902eab4524dc97f5\project.py", line 62, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-hsif3_67\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-hsif3_67\overlay\Lib\site-packages\sipbuild\project.py", line 241, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\Admin\AppData\Local\Temp\pip-build-env-hsif3_67\overlay\Lib\site-packages\pyqtbuild\builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by bytebutcher** [comment]
Thx, i will look into it!

**Comment by bytebutcher** [comment]
Hi there, sorry for the late update. i've ported dpp from Qt5 to Qt6 now. If you encounter any error, please let me know :)

**Comment by ViCrack** [comment]
thank you

**Comment by bytebutcher** [comment]
Decoder++ is now also backward-compatible to Qt5. As a result installation instructions slightly changed. In order to install the qt6 version following command needs to be executed:
```
pip3 install decoder-plus-plus[qt6]
```
Please see the <a href="https://github.com/bytebutcher/decoder-plus-plus/blob/master/INSTALL.md">Installation Guide<a/> for more information regarding individual setups. 

Please let me know if you encounter any errors.
